### ISSUE TITLE
buttonClasses?

### ISSUE THREAD

**Issue by Q1WP** [refactory-id/bootstrap-markdown#193]
It would also be nice to have an option for `buttonClasses` to override the source.  Not everyone uses btn-default.

This could also be an option of each individual button data.

**Comment by toopay** [comment]
We actually support `btnClass` for each button configuration, and it recognize most of known bootstrap's button classes, as you can see [here](https://github.com/toopay/bootstrap-markdown/blob/master/js/bootstrap-markdown.js#L110), so you can provide your own configuration on runtime if you really want to control individual button data.
